config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :drinks do
    resources :reviews
  end

  resources :reviews do
    resources :votes, only: [:create, :destroy]
  end

  root 'drinks#index'

end

app/models/drink.rb
class Drink < ActiveRecord::Base
  belongs_to :user
  has_many :reviews

  validates :name, presence: true
  validates :brand, presence: true
  validates :description, presence: true
  validates :volume, presence: true
  validates :caffeine, presence: true
  validates :calories, presence: true

  paginates_per 5

  mount_uploader :avatar, AvatarUploader

  def average_rating
    ratings = []
    reviews = Review.where("drink_id = ?", id)
    reviews.each do |review|
      ratings << review.rating
    end

    total = 0
    if ratings == []
      return 0
    end

    ratings.each do |rating|
      total += rating.to_f
    end

    (total/ratings.length).round(1)
  end

  def self.search(search)
    where("name ILIKE ? OR brand ILIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :drink
  belongs_to :user
  has_many :votes

  validates :body, presence: true
  validates :rating, presence: true

  def score
    score = 0
    self.votes.each do |vote|
      if vote.upvote == 1
        score += 1
      elsif vote.upvote == -1
        score -= 1 unless score == 0
      end
    end
    return score
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :drinks
  has_many :reviews
  has_many :votes

  mount_uploader :avatar, AvatarUploader

  def admin?
    role == "admin"
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :review
  belongs_to :user

  validates :user, presence: true
  validates :upvote, presence: true
  validates :user, uniqueness: { scope: :review }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:name, :avatar]
    devise_parameter_sanitizer.for(:account_update) << [:name, :avatar]
  end

end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  before_action :find_drink, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, except: [:index, :edit, :show, :new, :create, :destroy]

  def index
    @drinks = Drink.all
    if params[:search]
      @drinks = Drink.search(params[:search]).order("created_at DESC").page params[:page]
    else
      @drinks = Drink.all.order('created_at DESC').page params[:page]
    end
  end

  def show
    @reviews = Review.where(drink_id: @drink)
  end

  def new
    @drink = current_user.drinks.build
  end

  def create
    @drink = current_user.drinks.build(drink_params)

    if @drink.save
      redirect_to @drink
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @drink.update(drink_params)
      redirect_to @drink
    else
      render 'edit'
    end
  end

  def destroy
    @drink.destroy
    redirect_to root_path
  end

  private

  def find_drink
    @drink = Drink.find(params[:id])
  end

  def drink_params
    params.require(:drink).permit(:name, :brand, :description, :volume, :caffeine, :calories, :avatar)
  end

  def authorize_user
    if !user_signed_in? || !current_user.admin?
      raise ActionController::RoutingError.new("Not Found")
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def create
    @drink = Drink.find(params[:drink_id])
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.drink_id = @drink.id

    if @review.save
      ReviewMailer.new_review(@review).deliver_later
      redirect_to drink_path(@drink)
    else
      @vote = Vote.new
      redirect_to drink_path(@drink)
    end
  end

  private

  def review_params
    params.require(:review).permit(:body, :rating, :drink_id, :user_id)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!

  def create
    @review = Review.find(params[:review_id])
    @vote = Vote.new(upvote:vote_params,review:@review,user:current_user)

    if @vote.save
      respond_to do |format|
        format.html { redirect_to drink_path(@vote.review.drink) }
        format.json { render json: @vote.review.score }
      end
    else
      previous_vote = Vote.find_by(user: current_user, review: @review)
      if @vote.upvote == previous_vote.upvote
        previous_vote.destroy
      else
        previous_vote.update(upvote: @vote.upvote)
      end
      respond_to do |format|
        format.html { redirect_to drink_path(@vote.review.drink) }
        format.json { render json: @vote.review.score }
      end
    end
  end

  def destroy
  end

  private

  def vote_params
    params.require(:upvote)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def render_stars(value)
    output = ''
    if (1..5).include?(value.to_i)
      value.to_i.times { output += '*'}
    end
    output
  end

end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/drinks/_form.html.erb
<%= simple_form_for(@drink) do |f| %>
  <%= f.input :name %>
  <%= f.input :brand %>
  <%= f.input :description %>
  <%= f.input :volume %>
  <%= f.input :caffeine %>
  <%= f.input :calories %>
  <%= f.label :avatar, 'Add Picture' %>
  <%= f.file_field :avatar %>
  <%= f.button :submit %>
<% end %>

app/views/drinks/edit.html.erb
<header class="title-container">
  <div id="title">
    <h2>EnergyReview</h2>
  </div>

  <div id="login">
    <% if user_signed_in? %>
      <ul class='organizer'>
        <li>
          <% if current_user.avatar.url != nil %>
            <img id='header-img-size' src="<%= current_user.avatar.url %>"></img>
          <% end %>
        </li>
        <li><%= current_user.name %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      </ul>
    <% else %>
      <ul class='organizer'>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      </ul>
    <% end %>
  </div>
</header>

<h1>Edit Energy Drink</h1>
<%= render 'form' %>

app/views/drinks/index.html.erb
<header class="title-container">
  <div id="title">
    <h2>EnergyReview</h2>
  </div>

  <div id="login">
    <% if user_signed_in? %>
      <ul class='organizer'>
        <li>
          <% if current_user.avatar.url != nil %>
            <img id='header-img-size' src="<%= current_user.avatar.url %>"></img>
          <% end %>
        </li>
        <li><%= current_user.name %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      </ul>
    <% else %>
      <ul class='organizer'>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      </ul>
    <% end %>
  </div>

  <div id="search">
    <%= form_tag drinks_path, method: :get do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Drinks" %>
      <p><%= submit_tag "Search" %></p>
    <% end %>
  </div>
</header>

<p id="add">
<%= link_to "Add New ENERGY DRINK", new_drink_path %>
</p>

<div class="drink-container">
  <% @drinks.each do |drink| %>
    <div class="drink-container-box">
      <h3><%= link_to drink.name, drink %> by <%= drink.brand %></h3>
      <p><%= drink.reviews.count %> Comments</p>
    </div>
  <% end %>
</div>

<%= paginate @drinks %>

app/views/drinks/new.html.erb
<header class="title-container">
  <div id="title">
    <h2>EnergyReview</h2>
  </div>

  <div id="login">
    <% if user_signed_in? %>
      <ul class='organizer'>
        <li>
          <% if current_user.avatar.url != nil %>
            <img id='header-img-size' src="<%= current_user.avatar.url %>"></img>
          <% end %>
        </li>
        <li><%= current_user.name %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      </ul>
    <% else %>
      <ul class='organizer'>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      </ul>
    <% end %>
  </div>
</header>

<h3>Add New Energy Drink</h3>
<%= render 'form' %>

app/views/drinks/show.html.erb
<header class="title-container">
  <div id="title">
    <h2>EnergyReview</h2>
  </div>

  <div id="login">
    <% if user_signed_in? %>
      <ul class='organizer'>
        <li>
          <% if current_user.avatar.url != nil %>
            <img id='header-img-size' src="<%= current_user.avatar.url %>"></img>
          <% end %>
        </li>
        <li><%= current_user.name %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      </ul>
    <% else %>
      <ul class='organizer'>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      </ul>
    <% end %>
  </div>
</header>

<h1><%= @drink.name %></h1>
<h3>Brand: <%= @drink.brand %></h3>
<img id='drink-img-size' src="<%= @drink.avatar.url %>"></img>
<p>Description: <%= @drink.description %></p>
<p>Volume: <%= @drink.volume %> fluid ounces</p>
<p>Caffeine: <%= @drink.caffeine %> mg</p>
<p>Calories: <%= @drink.calories %></p>
<p>User: <%= @drink.user.name %></p>

<h2><%= pluralize(@drink.reviews.count, "Review") %> (<%= @drink.average_rating %> stars)</h2>

<div class="review-container">
  <div class="review-form">
    <%= render 'reviews/form' %>
  </div>

  <div>
    <% @reviews.each do |review| %>
      <ul class="review">
        <li>Rating: <%= render_stars(review.rating) %></li>
        <li class="author">By <%= review.user.name %></li>
        <li><%= review.body %></li>
        <li class="score">Score: <span class="score-tracker<%= review.id %>"><%= review.score %></span></li>
        <div class="votes">
          <%= link_to "Upvote", review_votes_path(review, upvote: 1), class: "upvote", id: review.id, :remote => "true", method: "post" %>
          <%= link_to "Downvote", review_votes_path(review, upvote: -1), class: "downvote", id: review.id, :remote => "true", method: "post" %>
        </div>
      </ul>
    <% end %>
  </div>
</div>

<%= link_to "Edit", edit_drink_path %>
<% if current_user.admin? || @drink.user_id == current_user.id %>
  <%= link_to "Destroy", drink_path(@drink), method: :delete, data: { confirm: "Are you sure? "} %>
<% end %>
<%= link_to "Home", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EnergyDrinkReview</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@drink, @drink.reviews.build]) do |f| %>
  <%= f.input :body, label: "Review" %>
  <%= f.input :rating, label: "Rating" %>
  <%= f.button :submit %>
<% end %>